<?php $session = new \Session; ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $title ?></title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
<hr>
<header>
    <div>
        <a href="/">Home</a>
    </div>
    <div>|</div>
    <div>
        <a href="/admin">Admin</a>
    </div>
    <div>|</div>
    <div>
        <a href="/admin/order/list">Order list</a>
    </div>
    <div>|</div>
    <div>
        <a href="/admin/user/logout">logout</a>
    </div>
</header>
<?php if ($message = $session->getMessage()): ?>
    <div class="message">
        <?= htmlspecialchars($message) ?>
    </div>
<?php endif; ?>
<hr>