<section class="container">
    <div class="login">
        <h1>Login</h1>
        <form method="post" action="/admin/user/login">
            <p><input class="login_input" type="text" name="login" value="" placeholder="login"></p>
            <p><input class="login_input" type="password" name="password" value="" placeholder="Password"></p>
            <p>
                <button class="add_product" type="submit">Login</button>
            </p>
        </form>
    </div>
</section>
</body>
</html>